### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by vegarringdal** [noppa/xmllint-wasm#8] opened 2022-09-22 13:03 UTC
![image](https://user-images.githubusercontent.com/2901416/191754107-3aaded86-a59e-48b3-99e3-855e8a6b8fe4.png)

Anyone seen this error?

**Comment by MLSTRM** [comment] 2023-03-08 20:47
I've also hit up against this recently.
From various bits of digging around I think it comes from a limitation in the build process, it seems by default emscripten gives a heap allocation of 16MB, which can be ok for smaller/simpler files but won't scale infinitely with your output.
From the emscripten docs in theory this project could be built with the "-s ALLOW_MEMORY_GROWTH" flag to allow for the memory to be increased as the process requires it, which would make it much more scalable for larger input files. This obviously opens up alternative issues in terms of potentially unbounded allocation causing the underlying process to die, but you'd then get a slightly more helpful memory allocation error from node itself rather than the current rather terse output.

**Comment by MLSTRM** [comment] 2023-03-09 11:12
@noppa is the above something you'd be open to? I'd be happy to raise the PR for the change if its not something you'd be likely to get too soon.

**Comment by noppa** [comment] 2023-03-09 11:53
Yeah, we should definitely fix this somehow. There's also relevant discussion in #1 about ways to reduce the memory consumption in the first place.

`-s ALLOW_MEMORY_GROWTH` seems useful but I'm a bit worried about safety implications, as the XML files could come from user data. Maybe we could even compile two versions, with and without that flag, and then use a flag like `allowMemoryGrowth: boolean` in the options that would switch wich build is used.

Even if we don't allow unlimited memory growth, I'm thinking the heap allocation limit could be adjusted to at least mitigate the problem. 16MB seems pretty low to me.

**Comment by MLSTRM** [comment] 2023-03-09 12:06
Yeah it feels reasonable to maybe only lift the restriction on the nodejs build for now since browsers are going to be a bit funnier about memory usage/allocation. In theory there is also the "-s MAXIMUM_MEMORY" flag just to set a higher upper limit while keeping the initial allocation at 16mb if you just want to allow it to grow some amount without an upper cap, but I agree that both options would be useful.
Personally at least for my usecase the unbounded option would be preferred since I'm running things in a nodejs lambda anyway so memory usage can be separately controlled and hard limited at the runtime level so I just want to let the process grow as much as it needs to.

**Comment by vegarringdal** [comment] 2023-03-09 13:39
I ended up with this one, dunno if its any help.
Needed it in the browser

https://github.com/vegarringdal/xmlvalidate.js

**Comment by noppa** [comment] 2023-03-09 13:51
@MLSTRM  Yeah personally my use case is the same, if the validation ends up crashing the whole process it's actually not the end of the world for me. But there may be other people with other use cases that are more sensitive to that stuff. So seems like an option to toggle it would be good.

Do `ALLOW_MEMORY_GROWTH` and `MAXIMUM_MEMORY` modify the wasm-file or just the JS wrapper that emscripten generates? Because the former is much bigger than the latter, so I'm a bit worried that having two versions of the wasm file in the same package is going to make the total disk size of this depdendency much bigger. For the JS wrapper I don't think it's that big of a deal.

Googling around a bit I think at least `MAXIMUM_MEMORY` only modifies the JS wrapper, so it could be possible to just use `ALLOW_MEMORY_GROWTH` and then if the options for _our wrapper_ don't have `allowMemoryGrowth: true`, we just use the JS wrapper that sets some sensible `MAXIMUM_MEMORY` or possibly even use the same JS wrapper and parameterize that emscripten option with some build magic trickery.

I have looked a bit into what they've done in that repo @vegarringdal linked to reduce memory usage (original discussion in #1), and I think we could probably do similar things here. But tbh I haven't had that much time to dive deeply into it, especially as my C skills aren't that great. I also don't want to loose the features that we currently have:

* Node.js support
* Ability to format the files, not just validate
* Ability to preload other xml or xsd files that the main files may import (I don't know if their implementation allows this or not)

**Comment by MLSTRM** [comment] 2023-03-09 14:14
I dug around a bit in the worker/wasm compiled output yesterday when looking into this and I think currently the issue is that the memory object gets implicitly created within the wasm source rather than passed in from the js wrapper, so it can't be easily resized - not sure exactly what the emscripten options will do to the compiled output (trying this out locally is on my list of things to play around it just not got that far yet) but I agree if we can have it so that the memory object is created in the wrapper up front and passed in as an import then it could be more easily parameterised at runtime as opposed to the fixed allocation it is currently.
That seems to make more sense overall since it would give you just a single compiled wasm file in theory. I'll try and play around with it a bit and see what changes it ends up making

**Comment by MLSTRM** [comment] 2023-03-09 15:32
OK so setting ALLOW_MEMORY_GROWTH seems to update the align on the memory instruction (setting allowed maximum) which is seemingly set to 2gb by default (since wasm emulates 32bit architecture I guess)
`  (memory (;0;) 256 16000)`
versus
`    (memory (;0;) 256 32768)`

The only other change is then a value in the node wrapper which seems to adjust the boundary check on the memory growth
`if (1048576E3 < a) return !1;` versus `if (2147483648 < a) return !1;`

In theory I guess you could then shim that value somehow in the node wrapper to allow it to be configured separately with the higher underlying align in the wasm but not totally sure how those 2 things would interact currently. 
It does however seem like there's a separate shared memory flag that should give us what we want here as it allows memory to be passed into the WebAssembly module instead of it creating its own, which would allow the size to be set programatically more easily

**Comment by MLSTRM** [comment] 2023-03-09 15:56
OK yeah this seems like the way to go. By using `-s IMPORTED_MEMORY` there are 2 useful options added to the Module generated which can be passed through at construction, either INITIAL_MEMORY as a number for size, or a WebAssembly.Memory object itself.
(relevant snippet of partially unminified source below)
`var D, C, za, E, F, G = opts.INITIAL_MEMORY || 16777216; 65536 <= G || x("INITIAL_MEMORY should be larger than STACK_SIZE, was " + G + "! (STACK_SIZE=65536)"); opts.wasmMemory ? z = opts.wasmMemory : z = new WebAssembly.Memory({ initial: G / 65536, maximum: G / 65536 });`
so those values could then be encapsulated and passed in via index-node.js / index-browser.mjs accordingly.
Not done too much work myself with workers before so not totally sure how to pass things down through into the module here but it does seem possible at least.

**Comment by noppa** [comment] 2023-03-09 16:54
Thanks for your investigation. I think I'll also have some time to check this out over the weekend. If you do want to take a look at this, though, I think the place to do the memory init is probably [worker-post.js](https://github.com/noppa/xmllint-wasm/blob/master/src/worker-post.js), which is ran _inside the Worker_ and has access to the [options from index.js](https://github.com/noppa/xmllint-wasm/blob/master/src/index.js#L99), and [initializes the Module](https://github.com/noppa/xmllint-wasm/blob/master/src/worker-post.js#L33).

**Comment by MLSTRM** [comment] 2023-03-10 12:57
Thanks for the pointer, managed to get it working and raised an initial PR here https://github.com/noppa/xmllint-wasm/pull/13
In the end I did have to set an overall memory cap because the linker gets funny about an unbounded memory size being passed in, but the cap is set to 4gb which is the maximum wasm will allow anyway so its effectively unbounded if you want to set it that far. Not setting the max memory will also take that assumption of the upper cap.
I was able to validate a 22MB file in just a couple of seconds using initial 256 / max 1800 (which works out around 113MB heap) and it seems like it scales fairly linearly with the input size which is a good sign at least.

**Comment by noppa** [comment] 2023-03-21 22:52
I have just published version 4.0.0 with @MLSTRM's memory limit options. Thanks again!
I also ended up raising the default max limit to double of the old default, 32MiB, which should even make the explicit memory limit options a bit less frequently required.
So I think we can finally close this one. If 32MiB isn't big enough, you can raise the maximum value up to 4GiB with 
```javascript
    maxMemoryPages: memoryPages.max,
```

**Closed as completed by noppa** 2023-03-21 22:52 UTC
